name: Run the robot framework integration tests

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "develop"
      - "main"

jobs:
  itest:

    strategy:
      fail-fast: false
      matrix:
        version: [ '3.8', '3.9', '3.10' ]

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}

      - name: Install requirements-dev.txt
        run: pip install -r requirements-dev.txt

      - name: Run integration tests
        run: make itest
